### ISSUE TITLE
Koodikatselmointi

### ISSUE THREAD

**Issue by Haimis** [MiikaProject/ot-harjoitustyo#1]
_Latasin projektin 10.12.2019 01:00_

Kerrassaan hyvännäköinen projekti! Koodi on laadukasta, siistiä ja kuvailevaa. Peli tekee minkä lupaa ja toimii vakaasti. Myös testit vaikuttivat järkeviltä ja checkstyle raportti oli yhtä metodia vaille puhdas.

Koodia katsellessani ja peliä pelatessani päädyin seuraaviin kehitysehdotuksiin.

**Käyttäjäkokemus:**
Merkittävin kehityskohde omaan silmään oli pelilaudan pieni koko ylipäätään ja suhteessa muuhun ohjelmaikkunaan. (kts. kuva). Vaatisi toki aika paljon refaktorointia hyllyjen kokojen ja sijaintien suhteen, mutta tekisi pelaamisesta miellyttävämpää.
![image](https://user-images.githubusercontent.com/44123397/70483099-285edc00-1af0-11ea-8cdb-64e1bcb31b03.png)

Uuden pelin aloittaessa nimi tuli aina asettaa uusiksi. Porukassa pelatessa toki perusteltua, mutta yksinäisen nörtin näkökulmasta hermostuttavaa. Tuota voisi kehittää esim. siten, että pelaaja pysyy lähtökohtaisesti samana, mutta on vaihdettavissa aloitusnäkymässä. Tai jopa moninpelin lisääminen siten, että ensin lisätään kaikki pelaajat ja pelinäkymään siirryttäessä näkyisi kuka on pelivuorossa.

**Arkkitehtuuri:**
Rankinglistan muodostaminen tapahtuu nyt luokassa RankingListView.java. Ei tuolle varmaan omaa kontrolleria kannata rakentaa, mutta sopisiko playerdaoon metodi, joka palauttaa suoraan viisi kärkitulosta tai vähemmän ja ne sitten vain iteroitaisiin view luokassa kohdilleen?

Tuo checkstylen herjaama metodi levelOne() kansiossa game/models/gamegrid tosiaan sisältää aika paljon toisteisuutta. Olisi varmaan mahdollista yksinkertaistaa siten, että Cell.java sisältäisi hyllyjen alku- ja loppukoordinaatit myös ja levelOne() sitten vaan kutsuisi uutta kahdella koordinaattiparilla ja värillä.

Jäin miettimään pakkausrakennetta, joka on kyllä selkeä ja perusteltu. Nykyinen rakenne helpottaa lukijaa ymmärtämään mitkä kontrollerit kuuluvat mihinkin näkymään jne. Toinen vaihtoehto olisi jakaa tiedostot ensin välillä view - model - controller ja sitten tarvittaessa alakansioihin, esim. views.primaryView. Tämä pohjaisi ehkä enemmän frontend - backend ajatteluun, jossa käyttöliittymää ja sovelluslogiikkaa kehitetään erikseen.

Luokassa PrimaryViewController.java syötteiden validoinnin voisi erottaa startGame() metodista omaksi metodikseen

Jouduin hetken etsimään metodia, jossa käsitellään tuotteiden kerääminen hyllystä. Intuitiivesti ajattelin olevan kontrollerien alla, mutta olikin sijainnissa game/models/GameGrid.java. [Wikipedian](https://fi.wikipedia.org/wiki/MVC-arkkitehtuuri) perusteella sijoittasin tällaiset toiminnallisuudet ennemmin kontrollereihin, mutta en kyllä ole varma kannastani.

**Pienemmät bugit**

Pelaajan nimeä syöttäessä pelkkiä välilyöntejä sisältävä nimi menee läpi. .trim() funktiolla tehty validointi hoitanee tuon bugin helposti.

**Jatkokehitysehdotukset**

Nopean pelailun perusteella ainakin kolmostasolla voittava taktiikka tuntui olevan rynniä kaikki hyllyt vauhdilla läpi. Toki tuo varmaan suoraviivaistuu, kun muistaa värit ulkoa, mutta yksi hauska lisäominaisuus voisi olla, että myös vääriä tuotteita voi kerätä mukaan käpelöimällä vääriä hyllyjä. Ne olisi sitten palautettava ennen kassaa tai vastaavasti vähentäisivät loppupisteitä.

**Comment by MiikaProject** [comment]
Hei.  Kiitos hyvästä palautteesta. 
* Olen samaa mieltä, että käyttäjäkokemus ei ole sovelluksessa optimaalinen. Varsinkin tuo ikkunan koko ja asioiden sijoittu siihen kaipaisi vielä säätöä. 
* Tuo pointti rankingListin muodostamisen sijoittamisesta DaO on hyvä. 
* Joo tuo levelOne() metodi on tarkoitus muokata järkevämmäksi. Yritin aiemmin kiireellä väsätä jotain toimivaa ja se on jäänyt pyörimään tuonne :)
* Tuo hyllyjen käsittelyyn liittyvän metodin sijaitseminen GameGrid luokassa periytyy siitä, että toteutin koko sovelluslogiikan aluksi siten, että ruudukko tulostui aina joka näppäimen painalluksella consoleen, eikä oikeaa javafx UI ollut olemassa. Siten tuo koko sovelluslogiikka osio päätyi tiukasti tuonne GameGrid osioon. 

Kiitos vielä palautteesta. Tsemppiä sulle loppukursiin ja mukavaa joululomaa :)

Miika
